### ISSUE TITLE
If "The language of the origin text" is not specified, tranlation doesn't work

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/assistant#198]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Open NC assistant
2. Go to *Translate*
3. Enter text to be translated
4. Under *The language of the origin text* DO NOT select any entry.
5. Select language to be translated to

### Expected behaviour
When nothing is specified unter *The language of the origin text*, the default "Detect language" should be automatically active.

### Actual behaviour
When clicking on Translate, the NC assistant is closed and an error message appears on the top right corner: Fehler des Assistenten: [object Object]✖ 

### Server configuration

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 8.3

**Nextcloud version:** 30.0.6

**App version translate2**: 2.0.3

**Comment by janepie** [comment]
Hello @DecaTec,
which version of Assistant do you use? This should be fixed in 2.3.0 with https://github.com/nextcloud/assistant/pull/167

Can you please update and see if it works?

**Comment by DecaTec** [comment]
Hi @janepie 
I'm currently on assistent version 2.4.0 and the problem still exists.

**Comment by janepie** [comment]
Which AI provider do you use for translation?

**Comment by DecaTec** [comment]
Translate2, the "new" ext. app for translations.

**Comment by janepie** [comment]
Ah yes, could have realized that, thanks :D 
I found a fix
